spring.application.name=ticket-api
spring.datasource.url=jdbc:mysql://localhost:3306/ticketdb
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root@1234

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect